permalink: pretty
markdown: kramdown

title: Centralny rejestr umów
author: Josh Davis &amp; Adam Dobrawy
description:
    Przekonaj swojego posła lub posłankę do poparcia realnej przejrzystości wydatków publicznych.
url: https://umowy.siecobywatelska.pl
repo: https://github.com/watchdogpolska/umowy
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
